services:
- type: web
  plan: free
  name: backend-spring
  env: docker
  rootDir: spring-backend
- type: web
  name: frontend
  env: static
  rootDir: frontend
  staticPublishPath: ./dist/frontend
  buildCommand: npm run build
- type: web
  name: backend-go
  env: go
  plan: free
  rootDir: backend-go
  buildCommand: go build -o rps .
  startCommand: ./rps
