services:
- type: web
  name: frontend
  env: static
  plan: free
  rootDir: frontend
  staticPublishPath: ./dist/frontend
  buildCommand: npm run build
- type: web
  name: backend-go
  env: go
  plan: free
  rootDir: backend-go
  buildCommand: go build -o rps .
  startCommand: ./rps
